local Data = require("src.world.original_area_data")
local Generator = require("src.world.classic_area_generator")

local Test = {}

local EXPECTED = {
    jungle = { height = 34, depths = 4, offset = 4, templates = 68 },
    ice = { height = 38, depths = 4, offset = 8, templates = 35 },
    temple = { height = 34, depths = 3, offset = 12, templates = 55 },
    olmec = { height = 55, depths = 1, offset = 15, templates = 13 },
}

local function fingerprint(level)
    local values = { level.area, level.seed, level.levelNumber, level.absoluteLevel }
    for y = 1, level.height do
        for x = 1, level.width do
            local tile = level.tiles[y][x]
            values[#values + 1] = tile.kind
            values[#values + 1] = tile.style or ""
        end
    end
    for _, row in ipairs(level.roomPath) do
        for _, value in ipairs(row) do values[#values + 1] = value end
    end
    for _, entity in ipairs(level.entities) do
        values[#values + 1] = entity.kind
        values[#values + 1] = entity.x
        values[#values + 1] = entity.y
    end
    return table.concat(values, "|")
end

local function validateLevel(area, seed, depth, checkDeterminism)
    local expected = EXPECTED[area]
    local level = Generator.generate(area, seed, { levelNumber = depth })
    assert(level.width == 42, area .. " width changed")
    assert(level.height == expected.height, area .. " height changed")
    assert(level.absoluteLevel == expected.offset + depth, area .. " level number changed")
    assert(#level.roomTemplates == 4, area .. " room rows changed")

    for roomY = 1, 4 do
        for roomX = 1, 4 do
            assert(#level.roomTemplates[roomY][roomX] == 80,
                area .. " produced a room that is not 10 x 8")
        end
    end

    if area ~= "olmec" then
        assert(level.entrance, area .. " has no entrance")
        assert(level.exit, area .. " has no exit")
        assert(level.startRoomY == 0, area .. " entrance room moved from the top row")
        assert(level.endRoomY == 3, area .. " exit room moved from the bottom row")
    else
        assert(level.entrance, "Olmec fixed room entrances were not imported")
        local bosses = 0
        for _, entity in ipairs(level.entities) do
            if entity.kind == "olmec" then bosses = bosses + 1 end
        end
        assert(bosses == 1, "Olmec fixed room must contain exactly one boss")
        assert(level.roomOrigins[4][1].y == 37, "Olmec lower chambers moved")
    end

    if checkDeterminism then
        local duplicate = Generator.generate(area, seed, { levelNumber = depth })
        assert(fingerprint(level) == fingerprint(duplicate), area .. " generation is not deterministic")
    end
end

function Test.run()
    for area, expected in pairs(EXPECTED) do
        assert(#Data[area].templates == expected.templates, area .. " template extraction count changed")
        for _, template in ipairs(Data[area].templates) do
            assert(#template == 80, area .. " source template is not 10 x 8")
        end
        for depth = 1, expected.depths do
            for seed = 1, 12 do validateLevel(area, seed, depth, seed == 1) end
        end
    end

    assert(#Data.olmecFixedInstances == 367, "Olmec fixed instance extraction changed")
    assert(Generator.generate("ice", 1, { levelNumber = 4 }).hasMoai,
        "The Moai must be generated by level 3-4")

    local foundCemetery = false
    local foundSacrificePit = false
    for seed = 1, 128 do
        foundCemetery = foundCemetery or Generator.generate("jungle", seed).hasCemetery
        foundSacrificePit = foundSacrificePit or Generator.generate("temple", seed).hasSacrificePit
    end
    assert(foundCemetery, "No Jungle cemetery appeared in the seed sample")
    assert(foundSacrificePit, "No Temple sacrifice pit appeared in the seed sample")
end

return Test
