return {
    flare_crate = require("src.platform.items.flare_crate"),
    lamp_item = require("src.platform.items.lamp_item"),
    lamp_red_item = require("src.platform.items.lamp_red_item"),
    flare = require("src.platform.items.flare"),
    arrow = require("src.platform.items.arrow"),
    rock = require("src.platform.items.rock"),
    ball = require("src.platform.items.ball"),
    jar = require("src.platform.items.jar"),
    skull = require("src.platform.items.skull"),
    chest = require("src.platform.items.chest"),
    locked_chest = require("src.platform.items.locked_chest"),
    crate = require("src.platform.items.crate"),
    gold_idol = require("src.platform.items.gold_idol"),
    key = require("src.platform.items.key"),
    die = require("src.platform.items.die"),
    bow = require("src.platform.items.bow"),
    machete = require("src.platform.items.machete"),
    mattock = require("src.platform.items.mattock"),
    mattock_head = require("src.platform.items.mattock_head"),
    pistol = require("src.platform.items.pistol"),
    shotgun = require("src.platform.items.shotgun"),
    teleporter = require("src.platform.items.teleporter"),
    web_cannon = require("src.platform.items.web_cannon"),
}
