#!/usr/bin/env python3
"""Extract immutable room-generation data from the original GM8 project."""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "original-game-reference/source/extracted/spelunky"
SCRIPT_DIRECTORY = SOURCE / "Scripts/Level Generation"

AREAS = {
    "jungle": "scrRoomGen2.gml",
    "ice": "scrRoomGen3.gml",
    "temple": "scrRoomGen4.gml",
    "olmec": "scrRoomGen5.gml",
}


def lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def extract_obstacles(source: str) -> dict[str, list[list[str]]]:
    obstacle_source = source.split("// Add obstacles", 1)[1].split("// Generate the tiles", 1)[0]
    obstacles: dict[str, list[list[str]]] = {}
    marker: str | None = None

    for line in obstacle_source.splitlines():
        marker_match = re.search(r'(?:else )?if \(tile == "(.)"\)', line)
        if marker_match:
            marker = marker_match.group(1)
            obstacles.setdefault(marker, [])
            continue

        if marker and re.search(r"if \(tile == .* or tile ==", line):
            marker = None

        if marker and "case " in line and "strObs" in line:
            rows = re.findall(r'strObs\d+\s*=\s*"([^"]+)"', line)
            if rows:
                obstacles[marker].append(rows)

    return obstacles


def extract_area(script_name: str) -> tuple[list[str], dict[str, list[list[str]]]]:
    source = (SCRIPT_DIRECTORY / script_name).read_text(encoding="utf-8")
    templates = re.findall(r'"([^"]{80})"', source)
    return templates, extract_obstacles(source)


def extract_olmec_instances() -> list[tuple[str, int, int]]:
    room = ET.parse(SOURCE / "Rooms/rOlmec.xml").getroot()
    included = {
        "oTemple",
        "oLavaSolid",
        "oLava",
        "oEntrance",
        "oCavemanWorship",
        "oHawkmanWorship",
        "oOlmec",
    }
    instances: list[tuple[str, int, int]] = []

    for instance in room.findall("./instances/instance"):
        object_name = instance.findtext("object")
        if object_name not in included:
            continue
        position = instance.find("position")
        assert position is not None
        instances.append((object_name, int(position.attrib["x"]), int(position.attrib["y"])))

    return instances


def render() -> str:
    lines = [
        "-- Generated by tools/extract_original_area_data.py.",
        "-- Do not edit: regenerate from the extracted GM8 source project.",
        "return {",
    ]

    for area_name, script_name in AREAS.items():
        templates, obstacles = extract_area(script_name)
        lines.append(f"    {area_name} = {{")
        lines.append(f"        source = {lua_string(script_name)},")
        lines.append("        templates = {")
        for template in templates:
            lines.append(f"            {lua_string(template)},")
        lines.append("        },")
        lines.append("        obstacles = {")
        for marker in sorted(obstacles):
            lines.append(f"            [{lua_string(marker)}] = {{")
            for rows in obstacles[marker]:
                rendered_rows = ", ".join(lua_string(row) for row in rows)
                lines.append(f"                {{ {rendered_rows} }},")
            lines.append("            },")
        lines.append("        },")
        lines.append("    },")

    lines.append("    olmecFixedInstances = {")
    for object_name, x, y in extract_olmec_instances():
        lines.append(f"        {{ object = {lua_string(object_name)}, x = {x}, y = {y} }},")
    lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: extract_original_area_data.py OUTPUT.lua")
    output = Path(sys.argv[1])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
