#!/usr/bin/env python3
"""Extract the original player and rope sprites used by the platforming prototype."""

from __future__ import annotations

import re
import shutil
import struct
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "original-game-reference/source/extracted/spelunky/Sprites"
PLAYER_SOURCE = SOURCE / "Character/Main Dude"
DESTINATION = ROOT / "assets/original/platform"
OUTPUT = ROOT / "src/platform/player_sprite_data.lua"

PLAYER_SPRITES = (
    "sStandLeft", "sRunLeft", "sLookRunL", "sDuckLeft", "sCrawlLeft",
    "sLookLeft", "sJumpLeft", "sFallLeft", "sStunL", "sHangLeft", "sPushLeft",
    "sClimbUp", "sClimbUp2", "sClimbUp3", "sDuckToHangL", "sWhoaLeft",
    "sAttackLeft",
)


def frame_key(path: Path) -> int:
    match = re.search(r"(\d+)$", path.stem)
    return int(match.group(1)) if match else 0


def png_size(path: Path) -> tuple[int, int]:
    with path.open("rb") as stream:
        header = stream.read(24)
    return struct.unpack(">II", header[16:24])


def lua_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def extract_player():
    records = {}
    for name in PLAYER_SPRITES:
        image_directory = PLAYER_SOURCE / f"{name}.images"
        frames = sorted(image_directory.glob("image *.png"), key=frame_key)
        root = ET.parse(PLAYER_SOURCE / f"{name}.xml").getroot()
        origin = root.find("origin")
        width, height = png_size(frames[0])
        output_directory = DESTINATION / "player" / name
        output_directory.mkdir(parents=True, exist_ok=True)
        paths = []
        for index, frame in enumerate(frames):
            output_path = output_directory / f"{index:03d}.png"
            shutil.copyfile(frame, output_path)
            paths.append(output_path.relative_to(ROOT).as_posix())
        records[name] = {
            "origin_x": int(origin.attrib["x"]),
            "origin_y": int(origin.attrib["y"]),
            "width": width,
            "height": height,
            "frames": paths,
        }
    return records


def extract_rope():
    rope_root = SOURCE / "Items/Weapons"
    destination = DESTINATION / "rope"
    destination.mkdir(parents=True, exist_ok=True)
    for name in ("sRope", "sRopeEnd", "sRopeTop"):
        frame = next((rope_root / f"{name}.images").glob("image *.png"))
        shutil.copyfile(frame, destination / f"{name}.png")


def extract_whip():
    weapon_root = SOURCE / "Items/Weapons"
    destination = DESTINATION / "whip"
    destination.mkdir(parents=True, exist_ok=True)
    for name in ("sWhipLeft", "sWhipRight", "sWhipPreL", "sWhipPreR"):
        frame = next((weapon_root / f"{name}.images").glob("image *.png"))
        shutil.copyfile(frame, destination / f"{name}.png")


def write_lua(records):
    lines = [
        "-- Generated by tools/extract_platform_sprites.py; do not edit by hand.",
        "return {",
    ]
    for name in PLAYER_SPRITES:
        record = records[name]
        lines.extend([
            f"    {name} = {{",
            f"        originX = {record['origin_x']}, originY = {record['origin_y']},",
            f"        width = {record['width']}, height = {record['height']},",
            "        frames = { " + ", ".join(lua_quote(path) for path in record["frames"]) + " },",
            "    },",
        ])
    lines.append("}")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    records = extract_player()
    extract_rope()
    extract_whip()
    write_lua(records)
    print(f"Extracted {sum(len(record['frames']) for record in records.values())} player frames")


if __name__ == "__main__":
    main()
