-- Generated by tools/extract_platform_sprites.py; do not edit by hand.
return {
    sStandLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sStandLeft/000.png" },
    },
    sRunLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sRunLeft/000.png", "assets/original/platform/player/sRunLeft/001.png", "assets/original/platform/player/sRunLeft/002.png", "assets/original/platform/player/sRunLeft/003.png", "assets/original/platform/player/sRunLeft/004.png", "assets/original/platform/player/sRunLeft/005.png" },
    },
    sLookRunL = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sLookRunL/000.png", "assets/original/platform/player/sLookRunL/001.png", "assets/original/platform/player/sLookRunL/002.png", "assets/original/platform/player/sLookRunL/003.png", "assets/original/platform/player/sLookRunL/004.png", "assets/original/platform/player/sLookRunL/005.png" },
    },
    sDuckLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sDuckLeft/000.png" },
    },
    sCrawlLeft = {
        originX = 9, originY = 8,
        width = 20, height = 16,
        frames = { "assets/original/platform/player/sCrawlLeft/000.png", "assets/original/platform/player/sCrawlLeft/001.png", "assets/original/platform/player/sCrawlLeft/002.png", "assets/original/platform/player/sCrawlLeft/003.png", "assets/original/platform/player/sCrawlLeft/004.png", "assets/original/platform/player/sCrawlLeft/005.png", "assets/original/platform/player/sCrawlLeft/006.png", "assets/original/platform/player/sCrawlLeft/007.png", "assets/original/platform/player/sCrawlLeft/008.png", "assets/original/platform/player/sCrawlLeft/009.png" },
    },
    sLookLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sLookLeft/000.png" },
    },
    sJumpLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sJumpLeft/000.png" },
    },
    sFallLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sFallLeft/000.png" },
    },
    sHangLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sHangLeft/000.png" },
    },
    sPushLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sPushLeft/000.png", "assets/original/platform/player/sPushLeft/001.png", "assets/original/platform/player/sPushLeft/002.png", "assets/original/platform/player/sPushLeft/003.png", "assets/original/platform/player/sPushLeft/004.png", "assets/original/platform/player/sPushLeft/005.png", "assets/original/platform/player/sPushLeft/006.png" },
    },
    sClimbUp = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sClimbUp/000.png", "assets/original/platform/player/sClimbUp/001.png", "assets/original/platform/player/sClimbUp/002.png", "assets/original/platform/player/sClimbUp/003.png", "assets/original/platform/player/sClimbUp/004.png", "assets/original/platform/player/sClimbUp/005.png" },
    },
    sClimbUp2 = {
        originX = 8, originY = 16,
        width = 16, height = 24,
        frames = { "assets/original/platform/player/sClimbUp2/000.png", "assets/original/platform/player/sClimbUp2/001.png", "assets/original/platform/player/sClimbUp2/002.png", "assets/original/platform/player/sClimbUp2/003.png", "assets/original/platform/player/sClimbUp2/004.png", "assets/original/platform/player/sClimbUp2/005.png", "assets/original/platform/player/sClimbUp2/006.png", "assets/original/platform/player/sClimbUp2/007.png", "assets/original/platform/player/sClimbUp2/008.png", "assets/original/platform/player/sClimbUp2/009.png", "assets/original/platform/player/sClimbUp2/010.png", "assets/original/platform/player/sClimbUp2/011.png" },
    },
    sClimbUp3 = {
        originX = 8, originY = 16,
        width = 16, height = 24,
        frames = { "assets/original/platform/player/sClimbUp3/000.png", "assets/original/platform/player/sClimbUp3/001.png", "assets/original/platform/player/sClimbUp3/002.png", "assets/original/platform/player/sClimbUp3/003.png", "assets/original/platform/player/sClimbUp3/004.png", "assets/original/platform/player/sClimbUp3/005.png", "assets/original/platform/player/sClimbUp3/006.png", "assets/original/platform/player/sClimbUp3/007.png", "assets/original/platform/player/sClimbUp3/008.png", "assets/original/platform/player/sClimbUp3/009.png", "assets/original/platform/player/sClimbUp3/010.png", "assets/original/platform/player/sClimbUp3/011.png" },
    },
    sDuckToHangL = {
        originX = 24, originY = 8,
        width = 32, height = 32,
        frames = { "assets/original/platform/player/sDuckToHangL/000.png", "assets/original/platform/player/sDuckToHangL/001.png", "assets/original/platform/player/sDuckToHangL/002.png", "assets/original/platform/player/sDuckToHangL/003.png", "assets/original/platform/player/sDuckToHangL/004.png", "assets/original/platform/player/sDuckToHangL/005.png", "assets/original/platform/player/sDuckToHangL/006.png", "assets/original/platform/player/sDuckToHangL/007.png", "assets/original/platform/player/sDuckToHangL/008.png" },
    },
    sWhoaLeft = {
        originX = 12, originY = 16,
        width = 24, height = 24,
        frames = { "assets/original/platform/player/sWhoaLeft/000.png", "assets/original/platform/player/sWhoaLeft/001.png", "assets/original/platform/player/sWhoaLeft/002.png", "assets/original/platform/player/sWhoaLeft/003.png", "assets/original/platform/player/sWhoaLeft/004.png", "assets/original/platform/player/sWhoaLeft/005.png", "assets/original/platform/player/sWhoaLeft/006.png" },
    },
    sAttackLeft = {
        originX = 8, originY = 8,
        width = 16, height = 16,
        frames = { "assets/original/platform/player/sAttackLeft/000.png", "assets/original/platform/player/sAttackLeft/001.png", "assets/original/platform/player/sAttackLeft/002.png", "assets/original/platform/player/sAttackLeft/003.png", "assets/original/platform/player/sAttackLeft/004.png", "assets/original/platform/player/sAttackLeft/005.png", "assets/original/platform/player/sAttackLeft/006.png", "assets/original/platform/player/sAttackLeft/007.png", "assets/original/platform/player/sAttackLeft/008.png", "assets/original/platform/player/sAttackLeft/009.png", "assets/original/platform/player/sAttackLeft/010.png" },
    },
}
